require(dplyr,quietly=TRUE,warn.conflicts=FALSE)
require(tidyr,quietly=TRUE)
require(janitor,quietly=TRUE)
require(ggplot2,quietly=TRUE)
require(xlsx,quietly=TRUE)
require(knitr,quietly = TRUE)
require(nlme,quietly = TRUE)
require(gridExtra,quietly = TRUE)
if(interactive())
  try(fortunes::fortune(), silent = TRUE)